### ISSUE TITLE
create two themes (light & dark) for the ff4j app

### ISSUE THREAD

**Issue by J-DK** [devs-from-matrix/ff4j-web-console#316]
**Is your feature request related to a problem? Please describe.**
The app needs to have two different themes (light & dark) and user should be able to switch the theme.

**Describe the solution you'd like**
Currently, use the material theme scheme for switching the themes.

**Describe alternatives you've considered**
Based on the analysis, we might use some other styling library for theming

**Comment by paul58914080** [comment]
Dark theme is now integrated

**Comment by paul58914080** [comment]
[Dark theme colors](https://materialtheme.arcsine.dev/?c=eyJwYWxldHRlIjp7InByaW1hcnkiOnsibWFpbiI6IiMyNjJhMzAiLCJsaWdodGVyIjoiI2JlYmZjMSIsImRhcmtlciI6IiMxNzE5MWUifSwiYWNjZW50Ijp7Im1haW4iOiIjMTJiNDdiIiwibGlnaHRlciI6IiNiOGU5ZDciLCJkYXJrZXIiOiIjMGE5YzVlIn0sIndhcm4iOnsibWFpbiI6IiNmZjdhMDAiLCJsaWdodGVyIjoiI2VhZDJiNyIsImRhcmtlciI6IiNhMzRiMDgifSwibGlnaHRUZXh0IjoiIzAwMDAwMCIsImxpZ2h0QmFja2dyb3VuZCI6IiNmYWZhZmEiLCJkYXJrVGV4dCI6IiNmOWZjZmYiLCJkYXJrQmFja2dyb3VuZCI6IiMyNjJhMzAifSwiZm9udHMiOlt7InRhcmdldCI6ImRpc3BsYXktNCJ9LHsidGFyZ2V0IjoiZGlzcGxheS0zIn0seyJ0YXJnZXQiOiJkaXNwbGF5LTIifSx7InRhcmdldCI6ImRpc3BsYXktMSJ9LHsidGFyZ2V0IjoiaGVhZGxpbmUiLCJsaW5lSGVpZ2h0Ijo0Mywic2l6ZSI6MzB9LHsidGFyZ2V0IjoidGl0bGUiLCJzaXplIjoyNCwic3BhY2luZyI6MC4yNX0seyJ0YXJnZXQiOiJzdWJoZWFkaW5nLTIiLCJsaW5lSGVpZ2h0IjoyNCwic3BhY2luZyI6MC4yNX0seyJ0YXJnZXQiOiJzdWJoZWFkaW5nLTEiLCJ2YXJpYW50IjoicmVndWxhciIsInNpemUiOjE0fSx7InRhcmdldCI6ImJvZHktMiIsInZhcmlhbnQiOiJyZWd1bGFyIiwibGluZUhlaWdodCI6MjAsInNpemUiOjE1fSx7InRhcmdldCI6ImJvZHktMSJ9LHsidGFyZ2V0IjoiYnV0dG9uIn0seyJ0YXJnZXQiOiJjYXB0aW9uIiwidmFyaWFudCI6ImxpZ2h0In0seyJ0YXJnZXQiOiJpbnB1dCIsInZhcmlhbnQiOiJsaWdodCIsInNpemUiOm51bGx9XSwiaWNvbnMiOiJGaWxsZWQiLCJsaWdodG5lc3MiOmZhbHNlfQ==)
